### ISSUE TITLE
Encoding/decoding in an autoregressive manner

### ISSUE THREAD

**Issue by shford7** [JooyoungLeeETRI/CA_Entropy_Model#11]
Hi,
First, congratulations on achieving a even better results in your most recent work! I do, though, have some confusions regarding the autoregressive model present in this paper. You mentioned that extracting <y_hat> can be done in parallel using binary masks, while this is not the case for decoding. My understanding is that this is because, during training/encoding, the actual values of y_hat are known so there is no need to encode y_hat explicitly, yet when decoding, all the model has is the encoded bitstream, so to decode the value of one pixel, the model has to decode its prior pixels first, thereby making it a sequential process. I am not entirely sure if my interpretation is correct. If it is, I wonder if you can please tell me, during decoding, what kind of assumptions do you make about the distribution parameters of the very first pixel you want to decode (as it has no prior pixels). Since it is surrounded by many zero's (due to padding), did you assume that the trained model, regardless of the actual value of the pixel, would believe that this pixel value follows the distribution of zeros (or zero-like) given its context? Sorry for the lengthy description and thank you very much for your patience!

**Comment by JooyoungLeeETRI** [comment]
Hi,
You fully understand the process of our model :-) The reason our encoder can estimate the model parameters in parallel is that all the y_hat representations are already known. Regarding the very initial contexts, as you mentioned, we just give zero-padded context values for the model parameter estimator f. 
For your information, after the publication, we've tried to utilize a sort of additional explicit contexts that indicate offsets from four spatial boarders of y_hat, to differentiate 'real 0' and 'padded 0'. However, the comparison results showed the two cases obtained the almost same results.

Hope this helps, and let me know if you have any further question.

**Comment by shford7** [comment]
Hi
Thank you very much for your prompt reply! I am still a bit baffled by the decoding process though, so I'd really appreciate it if you allow me to dig more into it, just for clarification. When started decoding, all the model has is a stream of completed not-yet-decoded strings, and it will start from pixel (0,0). The problem is, the model has no information about the value of this pixel (nor the distribution it follows). I wonder if you just set the value of pixel(0, 0) to some values and proceeds to the next pixel (using raster scanning), or did you explicitly feed some sort of 'pre-configured values' of mu and sigma for pixel (0,0) to the entropy model, allowing it to decode pixel(0,0) and proceeds to the following pixels? I was thinking the latter since it makes more sense for the distribution of the first pixel to follow that of zeros, despite its own value. If none of the above is the correct answer, I wonder if you can give me some insights on how you handle this particular issue? Thank you very much!

**Comment by JooyoungLeeETRI** [comment]
Hi,
All the model parameters are estimated by a network "f", even for the very initial point. Let's say that the decoder start a decoding process and it has no reconstructed y_hat representation.  (From here let me ignore the channel axis  to make it more clearer. All channels are processed together in our method.)

To estimate mu and sigma values for y_hat representations at (0,0), the decoder can estimate the mu and sigma values first via the estimator network f. Here, because the decoder do not have any pre-decoded representation yet, we just feed zero values, as contexts (c''), into the estimator network f. 

However, it should be noted that another type of available context (c') from the hyper-prior is fed into the estimator f, along with c''. Therefore, the obtained mu and sigma values for the position (0,0) may be different from image to image. In short, the obtained mu and sigma values for the position (0,0) are not pre-configured values, but the values dynamically determined by the network f, as for the other position.

After obtaining the mu and sigma values for the spatial position (0,0) from f, the decoder can retrieve symbols (representations of (0,0)) from the bitstream. These decoded representations are utilized again for the next symbol, in an auto-regressive manner.

You can find all these processes in our test code. That would be helpful for easy understanding.
Hope this helps!

**Comment by shford7** [comment]
Hi,

Thank you very much for your time and patience. Your reply is very informative and surely clear things up!
