### ISSUE TITLE
Training Codes

### ISSUE THREAD

**Issue by SachinG007** [JooyoungLeeETRI/CA_Entropy_Model#12]
Hi,
Thanks a lot for sharing such a wonderfully explained and easy to use codes.
I was wondering if it is possible to get the training codes, because I wanted to try to compress mel spectrograms using your method and compare, and hence wanted to train the models accordingly.

**Comment by JooyoungLeeETRI** [comment]
First of all, thank you for your interest and we're deeply sorry for the late response. (We missed the notification)

Regarding the training code, unfortunately, we don't have a plan at the moment, because of the issues we've mentioned in the previous issue (https://github.com/JooyoungLeeETRI/CA_Entropy_Model/issues/4).

We'll upload it later when it become possible.
Thank you!
