### ISSUE TITLE
Cross-platform encoding and decoding

### ISSUE THREAD

**Issue by joker-yp** [JooyoungLeeETRI/CA_Entropy_Model#14]
Dear Jooyoung,

Nowadays, I met a problem during participating in CLIC 2021.

When encoding and decoding on my local server, the reconstructed images look good, but when decoding on challenge docker environment, wrong reconstruction images got.
Now I find out it shall be caused by cross-platform issues, encode on one server and decoder on another one may cause wrong decode images. The network of my model is based on tensorflow-compression, also referred to your method.

So I would like to ask for your help, did you met cross-platform issue during past CLIC events? If so, how do you solve the problem.

Look forward to your reply! Thank you.

**Comment by JooyoungLeeETRI** [comment]
Dear Joker,

You may have several reasons for your issue.

One possible reason is the GPU operation that outputs slightly different results even on the same GPU (and of course on different GPUs). Those differences are very tiny, so most GPU-based applications can disregard them. However, in the compression domain, those tiny en-decoder mismatch make the decoding process impossible, because of cumulative error propagation on the entropy decoder. To prevent the mismatches, you should run the probability-related functions, in this case "h_s" and "f", on CPU. ("h_s" function on Balle'18 model, "Hyper Decdoer" and "Context Models" on Minnen'18 model)

Another reason might be mismatches between the runtime environments that your en/decoder source codes run on. I'm not an expert on this issue, so it's difficult to give you a technical advice, but you can try to use the same Docker image on both encoder and decoder sides. As far as I remember, CLIC provides several different types of Docker image for participants. For the last challenge, I also tried several types of images to prevent the en-decoder mismatch problem.

Hope this helps!!

**Comment by joker-yp** [comment]
Dear Jooyoung,

Thank you very much.

I've already pin our model on CPU during inference. But the error still happens.

Actually, I use same docker on encoder and decoder side. tensorflow/tensorflow:1.15.0-py3 (CPU) is the docker I used in the challenge. Did you remember the docker you used in the last challenge? Maybe I can try to docker image you used.

**Comment by joker-yp** [comment]
Dear Jooyoung,

Thank you very much.

I've already pin our model on CPU during inference. But the error still happens.

Actually, I use same docker on encoder and decoder side. tensorflow/tensorflow:1.15.0-py3 (CPU) is the docker I used in the challenge. Did you remember the docker you used in the last challenge? Maybe I can try to docker image you used.

**Comment by JooyoungLeeETRI** [comment]
Can you give me the list of Docker images? (We don't participate the challenge this year.)
I'll check it if you give me the list.

**Comment by joker-yp** [comment]
Hi Jooyoung,

Below image gives a list of Docker images.
Does it contain the image you used last year?

<img width="377" alt="屏幕截图 2021-03-02 222050" src="https://user-images.githubusercontent.com/61570027/109662054-98e69280-7ba5-11eb-8a17-168ba88c9fa2.png">

**Comment by JooyoungLeeETRI** [comment]
As far as I remember, we used an image whose name includes "tensorflow-compression", in which a different version(1.12x or 1.13x) of Tensorflow is installed. The list above doesn't seem to have the image. However, I'm not 100% sure for this. I'm so sorry.

One thing I clearly remember is that the image "tensorflow:1.15.0-xxx" is the first image we had tried last year. We met a similar cross-platform issue with that image, so we tried many different types images.

However, please note that last year we didn't use a docker image on the encoder side. That's why we tried several different images on the decoder side, so your compatibility issue may not come from the same reason as ours.

I'm so sorry again for this limited information. Please let me know if you need any further information.

**Comment by joker-yp** [comment]
![Screenshot_20210303-135845_Baidu](https://user-images.githubusercontent.com/61570027/109759838-a729c280-7c28-11eb-98a8-916ae3b975e6.jpg)
Thank you very much. I checked last years docker images, it seems the last one is what you used. I will check whether change runtime environment will works.
Johannes Balle told me that he thinks only integer network can solve the problem thoroughly, I will go deeper into the issue to find any possible solutions.
Please tell me if you have any suggestions. Thanks again.

**Comment by JooyoungLeeETRI** [comment]
Oh, I didn't know they still provide the last year's challenge submission interface. The image we used is "**gcr.io/clic-215616/compression:gpu (GPU)**". I'm 99% sure because we tested our model on both CPU and GPU version of the same image. To accelerate the inference time, we let some parts of our model run on GPUs.

Anyway, as Balle said, I also think the integer network proposed by him is the best solution. Another option for the challenge is debugging on the decoder side. (We did this last year to make sure that the estimated prob. parameters on the decoder side are exactly identical to those on the encoder side.)

Actually, even using the Docker image we used for the challenge, we didn't solve all the cross-platform issues last year, so we couldn't use our full model utilizing GMM-based prob. model, one key component proposed in our second model (https://arxiv.org/abs/1912.12817). Instead, we only used a simple single Gaussian-based model.

Hope you solve your issues and good luck on the CLIC2021 challenge!!!

**Comment by joker-yp** [comment]
Thank you so much.
It seems the image "gcr.io/clic-215616/compression:gpu (GPU)" is an extra images added by organizer, do you remember the specs of this image? What does it contain?

Talking about debugging, do you mean we should make sure Gaussian parameters μ and θ are identical on both side? Actually, I found they are not same since the output 'y' of encoder differs a little on different platform, do you how to fix this problem?

Yes, I've read your paper. So do you think GMM may also be a critical part for cross-platform issue? By the way, for the hyper-decoder, auto-regressive is still used in your submission, right?

**Comment by JooyoungLeeETRI** [comment]
I don't remember the spec exactly, but its version was lower than 1.15 as I mentioned above.

Regarding the μ and σ parameters, the decoder doesn't have to perform the encoding process. It only reconstructs the parameters from z_hat (and adjacent y_hat representations in the case of auto-regressive models), and the functions(networks) related to this process must run on CPU when those functions include floating-point computations. to guarantee the identical model parameters between en-decoder. If there's any en-decoder mismatch on the estimated parameters, even if it's very tiny, the decoding process may not be possible.

Conceptually, GMM modeling has nothing to do with the cross-platform issue. We just succeeded submission of the single Gaussian model, but failed the GMM model due to some cross-platform runtime issues. (Those were not due to the mentioned parameter mismatch. Unfortunately, we couldn't fine the reason.)  Both perform in an auto-regressive manner, and use the hyper-prior.

Hope this helps!

**Comment by joker-yp** [comment]
Hi Jooyoung,

During my test, μ and θ are different on different platforms, considering make them identical, I try to use quantized value during inference (use numpy.round and remain only one decimal place), in that way, it seems cross-platform issue can be avoided, to a certain extent. But if I remain two decimal place, the issue happens again. Absolutely quantize mean and variance to integer can also fix the issue, but bpp will increase a lot, it seems doubled.
How do you think about this solution?

BR,
Pei You

**Comment by JooyoungLeeETRI** [comment]
Hi Pei,

I tried a similar approach to overcome the cross-platform issue before, but It did not guarantee the correct decoding. As you said, the rounding operation may lessen the frequency of en-decoder mismatch, but there still remain a chance that the mismatch occurs (i.e. 0.4999999999999999 on encoder side and 0.5000....0001 on the decoder side.)

Regarding the performance loss, if you round the mean and variance values into integer format, it distorts the estimated distributions severely, thus leading to the significant performance loss. I think it's really difficult to avoid the performance loss, because most of the parameters, especially in the case of  σ, range from 0 to 1.

BTW, If you use CPU for running h_s (and auto-regressive prediction functions) on BOTH the encoder and decoder sides, the mismatch on the μ and σ parameters must not occur, from my experience. I guess you can fix that issue without the rounding operations.

Hope this helps!

**Comment by JooyoungLeeETRI** [comment]
I've corrected my typos from "θ" to "σ".

**Comment by joker-yp** [comment]
Hi Jooyoung,

Actually, we have four servers with different types of CPU. 
Core i9-9300, Xeon Silver 4210, Xeon Gold 5220 and Xeon E5 2690.
We tested on them, in which the first three can encode and decode on each other without any issue. But the last one always have the cross-platform issue.

I use all of them to encode the validation data, and then upload to CLIC. Although all of them reconstruct error images. But it seems the last one has the higher PSNR, means the least error.

I'm not sure whether different CPU could cause such big float point math error, but it seems true that I met a tough issue.

Thank you for your help. I will try to figure this out.

**Comment by JooyoungLeeETRI** [comment]
It's so strange to me. We've also tested various cross-platform environments based on different CPUs and  OSs (Windows and Ubuntu), but never met that kind of errors, at least, on the reconstructed μ and σ values.

If you still have any mismatch on the reconstructed μ and σ values (in the case of CPU inference), I think that's more important issue than anything else.

If you resolved the mismatch issue but still cannot normally reconstruct the images, I recommend you to try various docker images, including "gcr.io/clic-215616/compression:gpu (GPU)" and "gcr.io/clic-215616/compression:gpu (CPU)".

Good Luck!!

**Comment by joker-yp** [comment]
Dear Jooyoung, sorry for late response.

Currently, we simply the entropy model, make it the same as tensorflow_compression, without auto-regressive and Gaussian Mixture Likelihood, seems the cross-platform issue is avoided, to some extent.
Despite the loss of some quality, now we can correctly upload our results. Maybe the cross-platform issue will leave as a further study issue.

Thanks again.

**Comment by JooyoungLeeETRI** [comment]
I'm so sorry for late response. 
The cross-platform issue is always very complicated. Hope you deal with your issue well.

Anyway, I'll close this thread. If you need any further discussion, please open a new issue.
Thank you!
