### ISSUE TITLE
The model cannot be downloaded.

### ISSUE THREAD

**Issue by SunshineSki** [JooyoungLeeETRI/CA_Entropy_Model#18]
Excuse me, the model cannot be downloaded. Could you please provide a link to download the model?

**Comment by JooyoungLeeETRI** [comment]
I'm so sorry for late. You can download them via the link below:
https://drive.google.com/file/d/1NqIYWOJP4o_JbUl2n2SdxezZNVdpBw5c/view?usp=sharing

Please let me know if you still have any problem.

**Comment by Carcy** [comment]
I use the model, and have an issue that" You must feed a value for placeholder tensor 'prefix/Placeholder_2' with dtype float and shape [1,3,?,?]"

**Comment by JooyoungLeeETRI** [comment]
Hi Carcy,

I'm sorry for the unfriendly error message. The placeholder 2 is the input placeholder. Did you change the model? If so, please check if your input image is being correctly fed into the placeholder.

**Comment by Carcy** [comment]
I just input a png image of 416x240. Maybe, I use tensorflow2.3 and the new model was trained in lower or higher version of tensorflow? To avoid it, I use "import tensorflow.compat.v1 as tf" to compatible with lower versions.

**Comment by JooyoungLeeETRI** [comment]
We don't have any newer version of models. We just changed some testing procedures that utilize the same models as before. The models were trained on tensorflow 1.1x version.

Considering the error message, your problem seems more likely to come from some structural misuse, rather than the version compatibility issue. Why don't you run the original test code first? I think it helps you solve the problem.
