### ISSUE TITLE
Training code.

### ISSUE THREAD

**Issue by yash0307** [JooyoungLeeETRI/CA_Entropy_Model#4]
Thanks for sharing the test images. Do authors plan on releasing the training code ?

**Comment by JooyoungLeeETRI** [comment]
First of all, thank you for your interest. 
Unfortunately, we don't have a plan at the moment, because there're two issues on it.

We're working for an institute funded by Korean government, so sharing full codes possibly violates our regulations. In addition, the training codes needs heavy refactoring work, It may take more than a few days but we do not have enough resource because we're currently focusing on developing next models and preparing a challenge.

Of course, the first issue is more critical for us and if it can be resolved someday, we'd like to share the training code after refactoring. I'd appreciate if you understand our situation.
